SchemaVersion: 2018-07-01
Owner: "@mongodb/product-perf"
Description: |
  This workload is a mixed workload to test the maximum throughput that
  can be achieved by change event application (CEA). The workload starts Mongosync
  on a cluster with an empty initial dataset, waits for it to transition to
  CEA and then starts inserting documents on the source cluster.

Keywords:
- c2c
- replication
- cluster to cluster sync
- change event application
- CEA

EnvironmentVariables:
  MongosyncConnectionUrls: http://localhost:27182

Clients:
  Default:
    QueryOptions:
      maxPoolSize: 500

ScriptsPath: &scriptsPath ./MongosyncScripts.yml

Actors:

- Name: SetupSharding
  Type: AdminCommand
  Threads: 1
  Phases:
  - Repeat: 1
    Database: admin
    # We also run this on replica sets and so we
    # ignore if this command fails
    ThrowOnFailure: false
    Operations:
    - OperationMetricsName: EnableShardingMetrics
      OperationName: AdminCommand
      OperationCommand:
        enableSharding: db

  - Repeat: 1
    Database: admin
    ThrowOnFailure: false
    Operations:
    - OperationMetricsName: ShardCollectionMetrics
      OperationName: AdminCommand
      OperationCommand:
        shardCollection: db.Collection0
        key:
          _id: hashed
  - &nop {Nop: true}
  - *nop
  - *nop
  - *nop
  - *nop
  - *nop

- Name: Mongosync
  Type: ExternalScriptRunner
  Threads: 1
  Phases:
  - *nop
  - *nop
  - LoadConfig:
      Path: *scriptsPath
      Key: StartMongosync
  - LoadConfig:
      Path: *scriptsPath
      Key: PollForCEA
  - *nop
  - LoadConfig:
      Path: *scriptsPath
      Key: DrainWrites
  - LoadConfig:
      Path: *scriptsPath
      Key: Commit
  - LoadConfig:
      Path: *scriptsPath
      Key: WaitForCommit

- Name: InsertDocs
  Type: Loader
  Threads: 1
  Phases:
  - *nop
  - *nop
  - *nop
  - *nop
  - Repeat: 1
    BatchSize: 100
    Threads: 1
    DocumentCount: 500000
    Database: db

    # Note the document shape and number of collections doesn't
    # really matter here and we are generally just testing the
    # max throughput mongosync can achieve with an unbounded
    # insert workload
    CollectionCount: 1
    Document:
      a: {^RandomInt: {min: 0, max: 500000}}
      b: {^RandomString: {length: 8}}
      c: {^RandomString: {length: 20}}
  - *nop
  - *nop
  - *nop

  # Note that currently there is no autorun section in this workload as it is
  # being invoked manually
