# This workload file describes the evergreen patches and tasks that produced
# reliable data for
workload_name: qe_test_insert
Owner: Server Security
Description: |
  This workload evaluates the performance of Queryable Encryption against the established “Queryable Encryption Performance Release Criteria.”
patches:
  # This patch excludes the sharded test results
  ReplaceMeWithPatchID:
    linux-1-node-replSet-fle.2022-11:
      - medical_workload_states_100_0
      - medical_workload_states_95_5
      - medical_workload_states_50_50
      - medical_workload_diagnosis_100_0
      - medical_workload_diagnosis_95_5
      - medical_workload_diagnosis_50_50
      - medical_workload_status_100_0
      - medical_workload_status_95_5
      - medical_workload_status_50_50
      - medical_workload_credit_cards_100_0
      - medical_workload_credit_cards_95_5
      - medical_workload_credit_cards_50_50
      - medical_workload_guid_100_0
      - medical_workload_guid_95_5
      - medical_workload_guid_50_50
      - medical_workload_states_100_0_unencrypted
      - medical_workload_states_95_5_unencrypted
      - medical_workload_states_50_50_unencrypted
      - medical_workload_diagnosis_100_0_unencrypted
      - medical_workload_diagnosis_95_5_unencrypted
      - medical_workload_diagnosis_50_50_unencrypted
      - medical_workload_status_100_0_unencrypted
      - medical_workload_status_95_5_unencrypted
      - medical_workload_status_50_50_unencrypted
      - medical_workload_credit_cards_100_0_unencrypted
      - medical_workload_credit_cards_95_5_unencrypted
      - medical_workload_credit_cards_50_50_unencrypted
      - medical_workload_guid_100_0_unencrypted
      - medical_workload_guid_95_5_unencrypted
      - medical_workload_guid_50_50_unencrypted
      - medical_workload_guid_50_50_unencrypted
      - medical_workload_guid_50_50_unencrypted
    perf-3-shard-fle.arm.aws.2023-11:
      - medical_workload_states_100_0
      - medical_workload_states_95_5
      - medical_workload_states_50_50
      - medical_workload_diagnosis_100_0
      - medical_workload_diagnosis_95_5
      - medical_workload_diagnosis_50_50
      - medical_workload_status_100_0
      - medical_workload_status_95_5
      - medical_workload_status_50_50
      - medical_workload_credit_cards_100_0
      - medical_workload_credit_cards_95_5
      - medical_workload_credit_cards_50_50
      - medical_workload_guid_100_0
      - medical_workload_guid_95_5
      - medical_workload_guid_50_50
      - medical_workload_states_100_0_unencrypted
      - medical_workload_states_95_5_unencrypted
      - medical_workload_states_50_50_unencrypted
      - medical_workload_diagnosis_100_0_unencrypted
      - medical_workload_diagnosis_95_5_unencrypted
      - medical_workload_diagnosis_50_50_unencrypted
      - medical_workload_status_100_0_unencrypted
      - medical_workload_status_95_5_unencrypted
      - medical_workload_status_50_50_unencrypted
      - medical_workload_credit_cards_100_0_unencrypted
      - medical_workload_credit_cards_95_5_unencrypted
      - medical_workload_credit_cards_50_50_unencrypted
      - medical_workload_guid_100_0_unencrypted
      - medical_workload_guid_95_5_unencrypted
      - medical_workload_guid_50_50_unencrypted
      - medical_workload_guid_50_50_unencrypted
      - medical_workload_guid_50_50_unencrypted
genny_metrics:
  tests:
    - "InsertActor.load.inserts"
    - "InsertActor.FSM.update"
    - "InsertActor.FSM.query"
  metrics:
    - "OperationsTotal"
    - "DocumentsTotal"
    - "SizeTotal"
    - "DurationTotal"
    - "OverheadTotal"
    - "ErrorsTotal"
    - "AverageLatency"
    - "AverageSize"
    - "OperationThroughput"
    - "DocumentThroughput"
    - "SizeThroughput"
    - "LatencyMin"
    - "LatencyMax"
    - "Latency50thPercentile"
    - "Latency80thPercentile"
    - "Latency90thPercentile"
    - "Latency95thPercentile"
    - "Latency99thPercentile"
    - "WorkersMin"
    - "WorkersMax"
    - "ErrorRate"
storage_metrics:
  tests:
    - "crud_actor_qe Storage Metrics"
  metrics:
    - "Average Growth in /data/dbs/ (bytes/s)"
    - "End size of /data/dbs/ (bytes)"
timing_metrics:
  tests:
    - "medical_workload_states_100_0 Timing Metrics"
    - "medical_workload_states_95_5 Timing Metrics"
    - "medical_workload_states_50_50 Timing Metrics"
    - "medical_workload_diagnosis_100_0 Timing Metrics"
    - "medical_workload_diagnosis_95_5 Timing Metrics"
    - "medical_workload_diagnosis_50_50 Timing Metrics"
    - "medical_workload_status_100_0 Timing Metrics"
    - "medical_workload_status_95_5 Timing Metrics"
    - "medical_workload_status_50_50 Timing Metrics"
    - "medical_workload_credit_cards_100_0 Timing Metrics"
    - "medical_workload_credit_cards_95_5 Timing Metrics"
    - "medical_workload_credit_cards_50_50 Timing Metrics"
    - "medical_workload_guid_100_0 Timing Metrics"
    - "medical_workload_guid_95_5 Timing Metrics"
    - "medical_workload_guid_50_50 Timing Metrics"
    - "medical_workload_states_100_0_unencrypted Timing Metrics"
    - "medical_workload_states_95_5_unencrypted Timing Metrics"
    - "medical_workload_states_50_50_unencrypted Timing Metrics"
    - "medical_workload_diagnosis_100_0_unencrypted Timing Metrics"
    - "medical_workload_diagnosis_95_5_unencrypted Timing Metrics"
    - "medical_workload_diagnosis_50_50_unencrypted Timing Metrics"
    - "medical_workload_status_100_0_unencrypted Timing Metrics"
    - "medical_workload_status_95_5_unencrypted Timing Metrics"
    - "medical_workload_status_50_50_unencrypted Timing Metrics"
    - "medical_workload_credit_cards_100_0_unencrypted Timing Metrics"
    - "medical_workload_credit_cards_95_5_unencrypted Timing Metrics"
    - "medical_workload_credit_cards_50_50_unencrypted Timing Metrics"
    - "medical_workload_guid_100_0_unencrypted Timing Metrics"
    - "medical_workload_guid_95_5_unencrypted Timing Metrics"
    - "medical_workload_guid_50_50_unencrypted Timing Metrics"
    - "medical_workload_guid_50_50_unencrypted Timing Metrics"
    - "medical_workload_guid_50_50_unencrypted Timing Metrics"
  metrics:
    - "Total Duration (s)"
curator: "/perftooling/curator"
