SchemaVersion: 2018-07-01
Owner: "@10gen/dev-prod-tips"
Description: |
  This workload demonstrates the general workload substitution utility. You can use "LoadConfig"
  to load anything, even other workloads.

LoadConfig:
  Path: "./HelloWorld-ActorTemplate.yml"
  Parameters:
    # The non-templatized actor in the workload above has its name overridden,
    # but the parameters inside the actor template are NOT overridden, because
    # they are not evaluated until after the "ActorFromTemplate" is evaluated.
    #
    # You can always use `genny evaluate` on a workload yaml to see what it gets
    # preprocessed into.
    Name: Helloworld-Overridden
